--------------------------------------------------------------
-- Database table removal script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- note: spaces within table names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- Use this script to drop the tables created by -
--   'D:\British\Oracle\Assignemnt\SQL.sql'

-- Dropping a table has the effect of removing it from the Database.  All existing data is lost
-- as well as the definition of the table itself (stored as meta-data).  Dropping the tables allows
-- them to be re-created within the Database, even if they already exist.


--------------------------------------------------------------

-- Drop tables --

DROP TABLE fact_table CASCADE CONSTRAINT;

DROP TABLE dim_flights CASCADE CONSTRAINT;

DROP TABLE dim_time CASCADE CONSTRAINT;

DROP TABLE dim_compalint CASCADE CONSTRAINT;

DROP TABLE dim_customers CASCADE CONSTRAINT;


--------------------------------------------------------------
-- End of DDL DROP file auto-generation
--------------------------------------------------------------



-- Drop sqquence --
DROP sequence dim_flight_seq;
DROP sequence dim_time_seq;
DROP sequence dim_complain_seq;
DROP sequence dim_customer_seq;
DROP sequence fact_table_seq;
