DROP TABLE FlyU_flights CASCADE CONSTRAINTS;
DROP TABLE customer CASCADE CONSTRAINTS;
DROP TABLE complaint CASCADE CONSTRAINTS;


DROP TABLE flight_2018 CASCADE CONSTRAINTS;
DROP TABLE flight_2017 CASCADE CONSTRAINTS;